### ISSUE TITLE
Gas required exceeds limit

### ISSUE THREAD

**Issue by fulldecent** [ethereum/remix-ide#1114]
The error message "Gas required exceeds limit" is given for most any function call that fails a `require` function somewhere. Currently best practice for debugging is:

1. Remove one line of code from the end of the function you are calling
2. Redeploy the contract, set up all preconditions
3. Run the function again
4. Repeat until you don't get the error

This could be greatly improved with a DEBUG feature for failed transactions that works the same way as DEBUG for mined transactions.

**Comment by yann300** [comment]
It will soon be possible to execute a tx even if it fails (so it 'll allow debugging) + debugging node for ropsten, kovan, rinkeby will also be available, so that will make everything easier to debug failed txs.
Back a few month (year?) ago we thought adding a web3.debug function for the case you are describing.

**Comment by yann300** [comment]
it should now be possible to force sending a tx even if it fails. It would be great if you could double check with your use case.
I close now, but feel free to reopen
