### ISSUE TITLE
Refactor Renderer

### ISSUE THREAD

**Issue by serapath** [ethereum/remix-ide#1246]
Yesterday I fought a lot with the `Renderer` module while refactoring and figured it cannot be refactored away. It's a tricky module.

Basically it does nothing else then to render a `statusMessage`, which is kind of trivial, so one would think it was easy to just create some kind of visual "status message" component, so any module could just require that component when it needs to render a status... and a few places do exactly that...

BUT, a user can click on the rendered status message which causes a custom action defined where the status message is used, but additionally it also affects the: **file in the editor and a line/column position**

---

This is why it is tricky and the following options seem to exist:

1. I could either require the "status message" component where it is needed, but it needs to be aware of the `files` and `editor` in `app.js` which would mean i need to pass those components down the component tree everywhere in the app where a status message is needed, or otherwise - which is what we do instead - we need to pass `files` and `editor` to some kind of "Status Message Maker" (we call it RENDERER) and then we pass this one around the app wherever we need to create a "status message'.

2. There is one relatively obvious alternative, which is to just require and use the "status message" component directly where needed and when it's clicked, we trigger an event, that the parent component is re-emitting, until - similar to the DOM - the event just bubbles up until it reaches `app.js`, where we handle it, so the `editor` can highlight the lines and columns ... BUT this is a lot of emitting and re-emitting those events.

---

**So is there another option?**
The only other option I can imagine is to have some kind of global "event emitter" object, which any component can access to trigger something and everything else can listen to it so we would theoretically avoid
* passing lots of stuff down the component tree
* and we could also avoid bubbeling and re-bubbeling events a lot

...but it would get very confusing to track what is going on, so I am against the global "event emitter"

...**unless** we would have a way, that each trigger would provide a unique ID name of what triggered it and each listener also registered with a unique ID name

## Implications
This would always make it possible to turn on LOGGING and see messages logged exposing those IDs of all "senders" and "receivers" of all messages. That would keep debugging simple, because next to every message logged in the console, there would be the line number in the source code :-)

So if we find a way to do that nicely, it could have enormous benefits, because essentially it would enable us to get rid of basically most or all of the EVENTS we pass around every time we call a constructor with `new foobar(api, EVENTS, opts)` and in a way we could even get rid of the `api` object, because the global "event emitter" that tracks all senders and receivers via an ID could also be used to send messages (e.g. COMMANDS) directly to a certain ID instead of broadcasting it.

---

I have some ideas how this could work if you find this thought compelling in the first place - otherwise we probably rather leave everything like it is which keeps the code quite a bit more verbose than needed for everything we do i guess.

**Comment by yann300** [comment]
I think that deserve a closer look yes.

so for the Renderer issue, we could easily find a way to remove it or at least to make it nicer (by removing the dependency to the compiler/editor - even though that could add more verbosity). 
By look nicer I mean that now the dep to compiler/fileManager is only for the default `onclick`, there should be no default `onclick` and we should not require this dependency at the time of the `Renderer` instanciation.
So that goes a bit in favor of 1), for a first move, I think we should pass the clickCallback directly in the `renderer.error()` in the `opt` object.

But then yes having a globalEmitter would make sense:

For the global emitter you are proposing, that would means that instead of doing
`event.compiler.register(''compilationFinished",` () => {})`
we would do 
`globalEvent.register('compiler.compilationFinished', () => {})` (or something equivalent) ?

I think that in a way that goes against the idea of having this api and event object (the purpose was to keep modular connection between the app and the module by having this proxy api/event which only give the module what it needs).
But now at least these API object got very confused and we need to do something, so perhaps having a global event could be part of the solution.

**Comment by yann300** [comment]
ah ok, by unique ID name, I thought you were referring to a component, like `compiler`, `debugger`, ...
so in my example  `globalEvent.register('<component id>.<some action>', () => {})`
the first part is the unique id name.

**Comment by yann300** [comment]
moved to  https://github.com/ethereum/remix-ide/issues/1261
