### ISSUE TITLE
error: Failed to decode output: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by prashant-weiCrowd** [ethereum/remix-ide#1303]
I just deployed a contract on the remix with the environment `Javascript VM`. I send a transaction to contract (invoked non-constant function) and I didn't get a proper response. 

I could see long bytes as input but decoded input was {}. 

I tried checking if state variables are updated or not. I got hit by error:
`error: Failed to decode output: TypeError: Cannot read property 'length' of undefined` while accessing constant functions.

**Comment by yann300** [comment]
thanks for the report. could you please post the contract code?

**Comment by prashantprabhakar** [comment]
After debugging the issue, I realized that contract was not deployed properly. Once I increased the gas, I was able to call the functions and send transactions without any issue.

In previous versions, when gas is less while deploying contract, I get hit by `insufficient gas` error. But in this case, it took me 2 hours to figure out the issue. Since I could see the contract functions on left pan so I never thought that it is not deployed.

**Comment by dillonsvincent** [comment]
@prashantprabhakar I agree, this issue was causing me a headache until I read your comment. 
The "error: Failed to decode output: TypeError: Cannot read property 'length' of undefined " is caused by a failed contract creation but remix still returns the contract endpoints as if it were successful.

The work around is to view and expand the log output of the transaction for deploying the contract.

**Comment by kyriediculous** [comment]
@prashantprabhakar @dillonsvincent 
Thanks for the comments, ran into the same issue just now.

When looking at the status in the logs we can indeed see that the deployment of the contract failed.

0x0 Transaction mined but execution failed
--
to | Bounties.(constructor)
--

**Comment by comeonbuddy** [comment]
I also have this issue, but increase gas limit doesnt seem to help, my gas is already very high. I think it might be my contract code is too complicated. This is a bit annoying tho, I do not want to change my code. What should I do?

**Comment by dillonsvincent** [comment]
@comeonbuddy if this still happens on the main or test net, yes. But in js vm raise the gas as high as you need to get the tx to go through. Change the 4 to a 5 then 6 it will eventually go through

**Comment by yann300** [comment]
@comeonbuddy could you PM the contract code please? I would like to check whether it could be an issue with remix

**Comment by comeonbuddy** [comment]
@yann300 sure. how do I PM you, via email?

**Comment by comeonbuddy** [comment]
@dillonsvincent I was able to deploy it onto Rinkeby.

**Comment by yann300** [comment]
@comeonbuddy I can't find it in your repo ...

**Comment by comeonbuddy** [comment]
@yann300 sorry inside branch mileston-12

**Comment by paulhauner** [comment]
I also experienced this issue when deploying the code found in this contract (I copy/pasted it from Etherscan into Remix).

https://etherscan.io/address/0xbB902569a997D657e8D10B82Ce0ec5A5983C8c7C#code

Using Javascript VM and this url `https://remix.ethereum.org/#optimize=false&version=soljson-v0.4.24+commit.e67f0147.js`.

P.S. remix is awesome, thanks.

**Comment by comeonbuddy** [comment]
hey @yann300 any updates? I am curious to learn ur thoughts on this.

**Comment by yann300** [comment]
@comeonbuddy could you describe how you deploy the contract using your deploy script?
you can PM me at `gitter.com/yann300`

**Comment by ARitz-Cracker** [comment]
As a workaround, add a couple of extra zeros on the gas limit. A contract previously unable to deploy on the VM now deployes. https://puu.sh/AxgXh/406c25ff1e.png

**Comment by yann300** [comment]
The issue was that the deployment failed (out of gas) for very large contract but the contract interfact was still appended to the UI, that was confusing.
