### ISSUE TITLE
Use LESS or another CSS build tool

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#203]
Currently, CSS files are places in `assets/css/`. It would be nice moving `browser-solidity.css`, `styles.css`, `universal-dapp.css` to LESS and including it in the build process.

**Comment by jcbrmn** [comment]
I can take a look into this. Is there a PreProcessor that you prefer over another?

**Comment by axic** [comment]
Thanks @jcbrmn, that would be awesome!

I am a tiny bit familiar with *less* and *sass*, are there any others with similar following? I like *less*' syntax a bit better.

We also have a lot of current csslint warnings. Run `npm run csslint` locally to see them.

**Comment by jcbrmn** [comment]
There are other ones, but _less_ is more popular so I can go ahead and add _less_.

Thanks for the heads up about the csslint warnings. Will take a look at those as well.

**Comment by d2s** [comment]
Both _Less_ and _Sass_ are widely used, thought amount of Sass usage is growing much more.

- [LibSass](http://sass-lang.com/libsass) now has full support of Sass syntax.
- Larger projects (including [Bootstrap v4](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/)) are moving from Less to Sass, mainly because of larger community and faster compile process.

> “Moved from Less to Sass. Bootstrap now compiles faster than ever thanks to Libsass, and we join an increasingly large community of Sass developers.”

Comparing popularity of the projects can be difficult, but one metric is amount of downloads from npm repository. [npm-stat](https://npm-stat.com/) charts show amount of downloads for both: [less](https://npm-stat.com/charts.html?package=less&from=2016-01-01&to=2016-10-31) and [node-sass](https://npm-stat.com/charts.html?package=node-sass&from=2016-01-01&to=2016-10-31)

Based on those graphs, popularity of `less` has been relatively stable.
In comparison, popularity of LibSass–based `node-sass` has been growing a lot during the year.

### `less`
![screen shot 2016-10-31 at 00 47 58 less](https://cloud.githubusercontent.com/assets/135053/19840671/03a4dbdc-9f04-11e6-98b4-2091dd368815.png)

### `node-sass`
![screen shot 2016-10-31 at 00 47 45 node-sass](https://cloud.githubusercontent.com/assets/135053/19840672/07cfa516-9f04-11e6-8539-462ff363b8cb.png)



_Additional comparison:_
- [Should I learn Sass or Less for 2015?](https://www.quora.com/Should-I-learn-Sass-or-Less-for-2015)
- [Why Bootstrap 4 means Sass has won](http://developer.telerik.com/featured/why-bootstrap-4-means-sass-has-won/)
