### ISSUE TITLE
select text in terminal

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#2255]
it's not possible sometimes.

**Comment by hjlee9182** [comment]
I found how  to appear this problem.
When terminal input is show, select text in terminal doesn't work. 
Because terminal input space was been auto cursor.
![image](https://user-images.githubusercontent.com/46337218/64722731-00200b00-d50a-11e9-8006-7356403f1e63.png)
=> that's okay

![image](https://user-images.githubusercontent.com/46337218/64722759-0e6e2700-d50a-11e9-8412-5bdcd56123b7.png)
that's doesn't select text
