### ISSUE TITLE
handle receive and fallback functions

### ISSUE THREAD

**Issue by LianaHus** [ethereum/remix-ide#2505]
in recorder and to show in deploy and run

**Comment by Aniket-Engg** [comment]
Currently, as tested on remix-alpha, there are 3 cases:
1. only `fallback()` defined
In this case, this is working fine and same previous as this new fallback also has same `type: fallback` in the ABI.
2. only `receive()` defined
This is not being handled and not shown on UI as receive appears in ABI as `type:receive`. `receive()` is called when there is plain ether transfer and call to contract with empty calldata.
3. `fallback()` & `receive()` both defined
We show fallback on UI. But when user clicks on fallback without providing any calldata input, internally it goes to execute the receive function because of empty calldata.

**Comment by Aniket-Engg** [comment]
Closed by https://github.com/ethereum/remix-ide/pull/2531
