### ISSUE TITLE
Static analyzer - use the new AST format

### ISSUE THREAD

**Issue by axic** [ethereum/remix-ide#921]
Currently Remix uses `legacyAST`.

**Comment by axic** [comment]
@soad003 how much of a work would this be?

**Comment by soad003** [comment]
@axic good question, i depends on how different the new AST format is from the old one. I tried to keep all the directly AST dependant things in https://github.com/ethereum/remix/blob/master/remix-solidity/src/analysis/modules/staticAnalysisCommon.js. This should make changes a bit easier. Still hard to tell. Do you have a documentation of the new AST format i can use?

**Comment by axic** [comment]
I don't think we have a documentation, but the major difference is the reduced level of objects for children.

Please see the commandline compiler with `--ast-json` (old style) and `--ast-compact-json` (new style.

**Comment by axic** [comment]
@yann300 @soad003 @chriseth this would be extremely important, because it would allow us removing the legacy version we've kept for over 2 years because of this code.

What would it take to get this done? Would a Gitcoin grant/bounty help? cc @ceresstation @owocki

**Comment by axic** [comment]
@chriseth do we have a documentation listing differences?

**Comment by soad003** [comment]
Hi everyone, I am sorry that the old AST has become a burden. I agree that this has to be done and that it does not make sense to maintain two AST versions just because of the remix static analyser. 

I am currently pretty tight on time. So everything that helps me better understanding the AST changes makes it easier for me to squeeze this in somehow. But it will take me some time for sure.  

The changes necessary largely depend on how much the new representation differs from the old one. To get an idea of how much work it will be and if I can manage it, or if it comes close to a rewrite I need at least some information about the changes, e.g: 

- Did property names change 
- or node names
- are there new or removed AST node types?
- are there some properties on certain nodes that do not exist anymore
- Is the structure in general any difference apart form child nesting
- Is type information encoded any different (datatypes, nesting structures etc.) 

The static analyser uses all kinds of AST features and encodings to identify stuff. The answers to the questions above should give me some insight into how much work it is going to be.

**Comment by LianaHus** [comment]
@Aniket-Engg is this done?

**Comment by Aniket-Engg** [comment]
closed by https://github.com/ethereum/remix/pull/1427
