### ISSUE TITLE
Don't change from "pending"

### ISSUE THREAD

**Issue by sasayah** [ethereum/remix-ide#958]
<img width="1080" alt="2017-12-18 11 58 25" src="https://user-images.githubusercontent.com/26035905/34088222-3981cde6-e3eb-11e7-9b87-4664d9d1db4b.png">
In web3 Provider, I create contract, and "1 pending transactions" is  displayed in Run tab.
A while ago, I confirm that this transaction is captured. It can be cheked from browser-solidity and console.
But "1 pending transactions" has been displayed yet.
This is my code.

```
pragma solidity ^0.4.8;
contract HelloWorld {
  string public greeting;
  function HelloWorld(string _greeting) public {
    greeting = _greeting;
  }
  function setGreeting(string _greeting) public {
    greeting = _greeting;
  }
  function say() public constant returns (string) {
    return greeting;
  }
}
```

**Comment by yann300** [comment]
which backend are you using?

**Comment by sasayah** [comment]
I'm using Geth.
When I use JavaScript VM, there is no problem.

**Comment by iurimatias** [comment]
@sasayah do you still have this issue? I can't replicate this so it's probably been solved in the meanwhile

**Comment by albp** [comment]
I have the same problem.

**Comment by albp** [comment]
Perhaps is related to this "Invalid asm.js: Invalid member of stdlib"

**Comment by albp** [comment]
txRunner.js:200 Uncaught TypeError: Cannot read property 'transactionHash' of undefined
    at Object.callback (txRunner.js:200)
    at method.js:142
    at requestmanager.js:86
    at XMLHttpRequest.request.onreadystatechange (httpprovider.js:114)

**Comment by yann300** [comment]
@albp which backend are you using?

**Comment by albp** [comment]
@yann300 thx for ask.

I am using Web3 provider against a geth node exposing rpc.

I made this change and it works, but i tested only that the tool now detect the transaction with the contract just created, i dindt use this tool nor the contracts yet, i am learning.

```
function tryTillResponse(txhash, done) {
  executionContext.web3().eth.getTransactionReceipt(txhash, function (err, result) {
    //if (!err && !result) {
    if (err != null || result == null) { 

```

**Comment by yann300** [comment]
@albp would be great if you could post a PR with that change?

**Comment by albp** [comment]
My previous solution was only an adhoc solution for resolve fast my case, i dont know the logic of tryTillResponse to propose a solution, i think my previous solution could being forcing to retry in all errors, i think this could not be correct.

One "bug" seems that the execution arrives to the else option with "result" being undefined, in my case it arrives to the else with
    err.message === 'unknown transaction' and result undefined

I let the logic of the function like it was and in my case i added a check to the weird case of "unknown transaction" so forcing a retry in this case also, also changed the last result.transactionHash undefined possibility.

I think that the author of this function must think what is the intended logic of tryTillResponse described under (!err && !result)  and if must be changed or not, I do not consider myself qualified to propose a change.

```
function tryTillResponse (txhash, done) {
  executionContext.web3().eth.getTransactionReceipt(txhash, function (err, result) {
    if ((!err && !result) || (err && err.message === 'unknown transaction')) {
      // Try again with a bit of delay
      setTimeout(function () { tryTillResponse(txhash, done) }, 500)
    } else {
      done(err, {
        result: result,
        transactionHash: (result) ? result.transactionHash : null
      })
    }
  })
}

```

**Comment by yann300** [comment]
could you give a try on that fix?
https://github.com/ethereum/browser-solidity/pull/1102

**Comment by albp** [comment]
Your change is the same that i used first time, this change works in my case yes.

if (err || !result) 

but i think this change  hide all errors at app level, because it forced to retry always in case of an error.

The original (!err && !result) is better because its intend is to only retry in the weird case when there is no err and there is no result, then retry but when there is an error it dont retry but gives the app the oportunity to decide what to do with the error sending it to "done". With that change you could break the original intention of this function, i think. 

The real bug of this function was result null in the else case resolved with 
transactionHash: (result) ? result.transactionHash : null

And with that bug corrected my case error= "unknown transaction" function fails but gives an advice of that error in console but because at app level the error was ignored then the app dindt catch the transaction, trying to resolve my case at this low level function is not the solution i think but if you want to add this case at so low level i think that the if ((!err && !result) || (err && err.message === 'unknown transaction')) {  with a console.log of this weird situation will cause less future problems.

if you only want to know if the fix works in my case, then yes in my case it works now.

**Comment by yann300** [comment]
yes you are right,  this PR is just a fix.
we also need to pop up an alert after like 10 attempt
here is the issue: https://github.com/ethereum/browser-solidity/issues/1103

**Comment by yann300** [comment]
other issue has been opened https://github.com/ethereum/browser-solidity/issues/1103
